language: scala
scala:
   - 2.11.8

services:
  - postgresql

before_script:
  - psql -c "create database test; create user test with password 'test'; grant all privileges on database test to test;" -U postgres
